language: python
python:
  - '3.9'

addons:
  firefox: latest

branches:
  only:
    - dev_branch

before_script:
  - pip install -r requirements.txt
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
  - tar -xvzf geckodriver*
  - chmod +x geckodriver
  - sudo mv geckodriver /usr/local/bin/
  - pip install --upgrade sentry-sdk


env:
  global: 
    - DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - python manage.py test tests